---
permalink: legal-notices.html 
sidebar: sidebar 
keywords: legal notices, copyright, trademarks, open source, licenses 
summary: 'Mentions légales, droits d"auteur, marques déposées et informations sur la licence open source de NetApp Data Migrator.' 
---
= Mentions légales
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les mentions légales donnent accès aux déclarations de droits d'auteur, aux marques de commerce, aux brevets et plus encore.



== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marques déposées

NETAPP, le logo NETAPP et les marques figurant sur la page NetApp Trademarks sont des marques de NetApp, Inc. Les autres noms de sociétés et de produits peuvent être des marques de leurs propriétaires respectifs.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Brevets

Une liste actuelle des brevets détenus par NetApp peut être trouvée à :

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Politique de confidentialité

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Open source

Les fichiers de notification fournissent des informations sur les droits d'auteur et les licences de tiers utilisés dans les logiciels NetApp.

link:./media/data_migraotor_notice_2026.04.0_GA.pdf["Avis pour NetApp Data Migrator"^]
