---
sidebar: sidebar 
permalink: whats-new.html 
keywords: netapp, data, migrator, whats new, release, notes 
summary: Découvrez les nouveautés de ce site de documentation. 
---
= Nouveautés de NetApp Data Migrator
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de NetApp Data Migrator.



[[12-june-2026]]
== 12 juin 2026

NetApp Data Migrator 2026.06.0 améliore la précision, la fiabilité, l'évolutivité et la sécurité des migrations de données :

* Améliore la précision des migrations incrémentales et la préservation des métadonnées pour SMB grâce à l'inclusion de modes d'héritage d'autorisation configurables et à une synchronisation des métadonnées améliorée.
+
link:configure-bulk-migrate.html#inherited-permissions["Personnalisez une tâche de migration en masse"]

* Inclut des améliorations de performance et de stabilité pour les flux de travail de découverte, de migration et d'estampillage des autorisations pour NFS et SMB.




[[22-april-2026]]
== 22 avril 2026

NetApp Data Migrator 2026.04.0 propose une nouvelle solution pour la migration de fichiers de données. Vous pouvez utiliser NetApp Data Migrator pour migrer des données depuis des systèmes de stockage locaux ou tiers vers les services de stockage cloud NetApp. NetApp Data Migrator prend en charge les protocoles de transfert de fichiers NFS et SMB.

link:learn-about-data-migrator.html["En savoir plus sur NetApp Data Migrator"]
